# Generated by Django 2.0.1 on 2018-01-09 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('twitter', models.CharField(blank=True, default='', max_length=200)),
                ('facebook', models.CharField(blank=True, default='', max_length=200)),
                ('instagram', models.CharField(blank=True, default='', max_length=200)),
                ('youtube', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, default='', max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('ship_international', models.BooleanField()),
                ('currency', models.CharField(max_length=20)),
                ('price_max', models.PositiveIntegerField()),
                ('price_min', models.PositiveIntegerField()),
                ('avg_wait', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active_comment', models.CharField(choices=[('ACT', 'Active'), ('HIA', 'Hiatus'), ('CLO', 'Closed')], default='ACT', max_length=3)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approved', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_studio_created', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
