# Generated by Django 2.0.1 on 2018-01-09 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
